In [35]:
import pandas as pd
import numpy as np
import datetime

In [10]:
df_wine = pd.read_csv('C:\\Users\\Igori\\Documents\\Projects\\Bootcamp\\Modulo_2\\Desafio\\winequality-red.csv', sep=";")

In [11]:
df_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [12]:
df_wine.shape

(1599, 12)

In [13]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [15]:
df_wine.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [16]:
print("Tipos de dados existentes do dataset: \n{}".format(df_wine.dtypes.value_counts()))

Tipos de dados existentes do dataset: 
float64    11
int64       1
dtype: int64


In [18]:
print("Tipos de dados existentes do dataset: {}".format(df_wine.dtypes.nunique()))

Tipos de dados existentes do dataset: 2


In [20]:
print("Proporção de valores nulos para variável 'residual sugar': {}% ".format((len(df_wine['residual sugar'])/df_wine.isnull().sum()["residual sugar"])))

Proporção de valores nulos para variável 'residual sugar': inf% 


C:\Users\Igori\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in longlong_scalars
  """Entry point for launching an IPython kernel.


In [21]:
df_wine.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [22]:
df_wine.median()

fixed acidity            7.90000
volatile acidity         0.52000
citric acid              0.26000
residual sugar           2.20000
chlorides                0.07900
free sulfur dioxide     14.00000
total sulfur dioxide    38.00000
density                  0.99675
pH                       3.31000
sulphates                0.62000
alcohol                 10.20000
quality                  6.00000
dtype: float64

In [30]:
print("Quantidade de vinhos com qualidade igual a 5: \n", df_wine['quality'].value_counts())

Quantidade de vinhos com qualidade igual a 5: 
 5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64


In [38]:
df = df_wine['fixed acidity'].values

In [39]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
dataset = scaler.fit_transform(np.array(df.reshape(-1,1)))

In [40]:
dataset.min()

0.0

In [42]:
df_wine['fixed acidity'] =scaler.fit_transform(np.array(df_wine['fixed acidity'].values.reshape(-1,1)))
df_wine['volatile acidity'] =scaler.fit_transform(np.array(df_wine['volatile acidity'].values.reshape(-1,1)))
df_wine['citric acid'] =scaler.fit_transform(np.array(df_wine['citric acid'].values.reshape(-1,1)))
df_wine['residual sugar'] =scaler.fit_transform(np.array(df_wine['residual sugar'].values.reshape(-1,1)))
df_wine['chlorides'] =scaler.fit_transform(np.array(df_wine['chlorides'].values.reshape(-1,1)))
df_wine['free sulfur dioxide'] =scaler.fit_transform(np.array(df_wine['free sulfur dioxide'].values.reshape(-1,1)))
df_wine['total sulfur dioxide'] =scaler.fit_transform(np.array(df_wine['total sulfur dioxide'].values.reshape(-1,1)))
df_wine['density'] =scaler.fit_transform(np.array(df_wine['density'].values.reshape(-1,1)))
df_wine['pH'] =scaler.fit_transform(np.array(df_wine['pH'].values.reshape(-1,1)))
df_wine['sulphates'] =scaler.fit_transform(np.array(df_wine['sulphates'].values.reshape(-1,1)))
df_wine['alcohol'] =scaler.fit_transform(np.array(df_wine['alcohol'].values.reshape(-1,1)))


In [43]:
df_wine['fixed acidity'].min()

0.0

In [44]:
df_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.247788          0.397260         0.00        0.068493   0.106845   
1       0.283186          0.520548         0.00        0.116438   0.143573   
2       0.283186          0.438356         0.04        0.095890   0.133556   
3       0.584071          0.109589         0.56        0.068493   0.105175   
4       0.247788          0.397260         0.00        0.068493   0.106845   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.140845              0.098940  0.567548  0.606299   0.137725   
1             0.338028              0.215548  0.494126  0.362205   0.209581   
2             0.197183              0.169611  0.508811  0.409449   0.191617   
3             0.225352              0.190813  0.582232  0.330709   0.149701   
4             0.140845              0.098940  0.567548  0.606299   0.137725   

    alcohol  quality  
0  0.153846        5  
1  0.215385        5  
2  0.215385        5  
3  0.215385        6  
4  0.153846        5

In [45]:
import pylab as pl # utilizado para plotar os gráficos
from sklearn import neighbors, datasets

In [48]:
X = df_wine.iloc[:, :-1].values
y = df_wine.iloc[:,11].values

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [51]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [53]:
y_pred = classifier.predict(X_test)

In [54]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[  1   0   1   0   0   0]
 [  0   1  14   5   1   0]
 [  0   0 148  54   5   0]
 [  0   1  71 102  21   0]
 [  0   1   9  23  19   0]
 [  0   0   0   1   2   0]]
              precision    recall  f1-score   support

           3       1.00      0.50      0.67         2
           4       0.33      0.05      0.08        21
           5       0.61      0.71      0.66       207
           6       0.55      0.52      0.54       195
           7       0.40      0.37      0.38        52
           8       0.00      0.00      0.00         3

    accuracy                           0.56       480
   macro avg       0.48      0.36      0.39       480
weighted avg       0.55      0.56      0.55       480



C:\Users\Igori\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred_TreeClassifier = clf.predict(X_test)

In [60]:
print(confusion_matrix(y_test,y_pred_TreeClassifier))
print(classification_report(y_test,y_pred_TreeClassifier))

[[  0   0   0   2   0   0]
 [  2   3   9   4   3   0]
 [  0   7 146  40  14   0]
 [  0   5  59 109  22   0]
 [  0   0   3  15  32   2]
 [  0   0   0   0   2   1]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.20      0.14      0.17        21
           5       0.67      0.71      0.69       207
           6       0.64      0.56      0.60       195
           7       0.44      0.62      0.51        52
           8       0.33      0.33      0.33         3

    accuracy                           0.61       480
   macro avg       0.38      0.39      0.38       480
weighted avg       0.61      0.61      0.60       480



In [61]:
from sklearn.svm import SVC
clf_Svc = SVC(gamma='auto', kernel='rbf')
clf_Svc = clf_Svc.fit(X_train,y_train)
y_pred_SVM = clf_Svc.predict(X_test)

In [63]:
print(confusion_matrix(y_test,y_pred_SVM))
print(classification_report(y_test,y_pred_SVM))

[[  0   0   2   0   0   0]
 [  0   0  16   5   0   0]
 [  0   0 177  30   0   0]
 [  0   0  91 104   0   0]
 [  0   0   6  46   0   0]
 [  0   0   0   3   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        21
           5       0.61      0.86      0.71       207
           6       0.55      0.53      0.54       195
           7       0.00      0.00      0.00        52
           8       0.00      0.00      0.00         3

    accuracy                           0.59       480
   macro avg       0.19      0.23      0.21       480
weighted avg       0.49      0.59      0.53       480



C:\Users\Igori\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [65]:
from sklearn.neural_network import MLPClassifier
clf_MLP = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5,5),random_state=1)
clf_MLP = clf_MLP.fit(X_train,y_train)
y_pred_MLP = clf_MLP.predict(X_test)

C:\Users\Igori\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [66]:
print(confusion_matrix(y_test,y_pred_MLP))
print(classification_report(y_test,y_pred_MLP))

[[  0   0   2   0   0   0]
 [  0   0  12   8   1   0]
 [  0   0 161  45   1   0]
 [  0   0  61 112  22   0]
 [  0   0   4  31  17   0]
 [  0   0   0   1   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        21
           5       0.67      0.78      0.72       207
           6       0.57      0.57      0.57       195
           7       0.40      0.33      0.36        52
           8       0.00      0.00      0.00         3

    accuracy                           0.60       480
   macro avg       0.27      0.28      0.27       480
weighted avg       0.56      0.60      0.58       480



C:\Users\Igori\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [68]:
from sklearn.ensemble import RandomForestClassifier
clf_random = RandomForestClassifier(max_depth=10, random_state=1)
clf_random =clf_random.fit(X_train,y_train)
y_pred_Random = clf_random.predict(X_test)

In [69]:
print(confusion_matrix(y_test,y_pred_Random))
print(classification_report(y_test,y_pred_Random))

[[  0   0   2   0   0   0]
 [  0   0  14   7   0   0]
 [  0   0 167  38   2   0]
 [  0   0  46 136  13   0]
 [  0   0   5  24  23   0]
 [  0   0   0   1   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        21
           5       0.71      0.81      0.76       207
           6       0.66      0.70      0.68       195
           7       0.57      0.44      0.50        52
           8       0.00      0.00      0.00         3

    accuracy                           0.68       480
   macro avg       0.32      0.32      0.32       480
weighted avg       0.64      0.68      0.66       480



C:\Users\Igori\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [88]:
a = y
a = np.where(a>5, 1,np.where(a<=5, 0,a))
print(len(a[a==0]))
print(len(a[a==1]))
print(len(a[a==0])+len(a[a==1]))
print(len(y))
y=a

744
855
1599
1599


In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [90]:
clf_random_2 = RandomForestClassifier(max_depth=10, random_state=1)
clf_random_2 =clf_random_2.fit(X_train,y_train)
y_pred_Random_2 = clf_random_2.predict(X_test)

In [91]:
print(confusion_matrix(y_test,y_pred_Random_2))
print(classification_report(y_test,y_pred_Random_2))

[[186  44]
 [ 50 200]]
              precision    recall  f1-score   support

           0       0.79      0.81      0.80       230
           1       0.82      0.80      0.81       250

    accuracy                           0.80       480
   macro avg       0.80      0.80      0.80       480
weighted avg       0.80      0.80      0.80       480



In [92]:
from scipy import stats 
stats.pearsonr(df_wine['fixed acidity'],df_wine['pH'])

(-0.6829781945685313, 4.06303403984837e-220)

In [93]:
stats.pearsonr(df_wine['quality'],df_wine['alcohol'])

(0.476166324001136, 2.831476974778582e-91)

In [94]:
df_wine2 = pd.read_csv('C:\\Users\\Igori\\Documents\\Projects\\Bootcamp\\Modulo_2\\Desafio\\winequality-red.csv', sep=";")

In [96]:
from scipy import stats 
stats.pearsonr(df_wine2['fixed acidity'],df_wine2['pH'])

(-0.6829781945685313, 4.06303403984837e-220)

In [97]:
stats.pearsonr(df_wine2['quality'],df_wine2['alcohol'])

(0.476166324001136, 2.831476974778582e-91)